// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgadxvfvcpimlwyrbbhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnYWR4dmZ2Y3BpbWx3eXJiYmh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMjEwNjIsImV4cCI6MjA1OTg5NzA2Mn0.d06Fyi8fuSPDhIJdx8WA1-6Muy95FkFXrqLo-48kucQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);